name: Sputnik
options:
  bundleIdPrefix: Viktor-Volkov
  minimumXcodeGenVersion: 2.5.0
  deploymentTarget:
    iOS: "10.0"
  groupSortPosition: top
  developmentLanguage: ru
  postGenCommand: pod install
settings:
  base:
    TARGETED_DEVICE_FAMILY: 1
    MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS: YES
    GCC_PREPROCESSOR_DEFINITIONS:
      - "\"var=__auto_type\""
      - "\"let=__auto_type const\""
      - "PUBLIC=1"
    CODE_SIGN_STYLE: Manual
  configs:
    debug:
      AP_NAME: Sputnik debug
      PROVISIONING_PROFILE_SPECIFIER: 'Sputnik Development'
      PRODUCT_BUNDLE_IDENTIFIER: com.dev.suai.sputnik
    release:
      AP_NAME: Спутник ГУАП
      PROVISIONING_PROFILE_SPECIFIER: 'XC iOS: Viktor-Volkov.SUAI-Navigation'
      PRODUCT_BUNDLE_IDENTIFIER: Viktor-Volkov.SUAI-Navigation
targets:
  Sputnik:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    productType: application
    devices: iPhone
    sources:
      - path: Sputnik
        excludes:
          - "Resources/Information/information.json"
          - "Resources/Navigation/"
    settings:
      TARGETED_DEVICE_FAMILY: 1
